#cloud-config
%{ if length(ssh_keys) > 0 }
ssh_authorized_keys:
%{ for ssh_key in ssh_keys }
- ${ssh_key}
%{ endfor }
%{ endif }
runcmd:
- DEBIAN_FRONTEND=noninteractive apt-get update
- DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common jq awscli
- DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
